---
title: "IGP Level 1 and 2 Facilities"
author: "Chris Lopez"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    social: menu
    source_code: embed
runtime: shiny
---

```{r global, include=FALSE}
library(leaflet)
library(shiny)
library(dplyr)
library(readxl)
library(DT)
library(shinydashboard)
library(ggplot2)
library(plotly)
library(treemap)
library(highcharter)

# Load polygons of watershed management areas
wma <- geojsonio::geojson_read("json/wma.json", what = "sp")

# Create a color palette for watershed polygons
pal <- colorFactor(c("#1F77B4", "#AEC7E8", "#FF7F0E", "#FFBB78", 
                     "#2CA02C", "#98DF8A", "#D62728", "#FF9896", 
                     "#9467BD", "#C5B0D5", "#8C564B", "#C49C94", 
                     "#E377C2", "#F7B6D2", "#7F7F7F", "#C7C7C7", 
                     "#BCBD22", "#DBDB8D", "#17BECF", "#9EDAE5"), 
                   NULL)

# Load csv of IGP facility data
sites <- read_excel("data/smarts_data_2018-12-14.xls", col_types = "text") %>% 
  as.data.frame()

sites$Latitude <- as.numeric(sites$Latitude)
sites$Longitude <- as.numeric(sites$Longitude)
names(sites) <- make.names(names(sites))
sites$Level <- factor(sites$Level)
```

Inputs {.sidebar data-width=300}
-----------------------------------------------------------------------

```{r}
 shiny::selectInput("Level", label = h3("Level"), 
    choices = list("All Level 1 and Level 2 Facilities", "Level 1", "Level 2"), 
    selected = "All Level 1 and Level 2 Facilities")
```

```{r}
 shiny::selectInput("Pollutant", label = h3("Pollutant"), 
    choices = list("All Pollutants" = "All Pollutants",
                   "Aluminum, Total (Recoverable)" = "Aluminum, Total (Recoverable)",
                   "Ammonia, Total (as N)" = "Ammonia, Total (as N)",             
                   "Biochemical Oxygen Demand (BOD) (5-day @ 20 Deg. C)" = 
                     "Biochemical Oxygen Demand (BOD) (5-day @ 20 Deg. C)",
                   "Cadmium, Total (Recoverable)" = "Cadmium, Total (Recoverable)",
                   "Chemical Oxygen Demand (COD)" = "Chemical Oxygen Demand (COD)",
                   "Copper, Total (Recoverable)" = "Copper, Total (Recoverable)",
                   "Cyanide, Total (as CN)" = "Cyanide, Total (as CN)",                     
                   "Iron, Total (Recoverable)" = "Iron, Total (Recoverable)",
                   "Lead, Total (Recoverable)" = "Lead, Total (Recoverable)",           
                   "Magnesium, Total (Recoverable)" = "Magnesium, Total (Recoverable)", 
                   "Nitrite Plus Nitrate (as N)" = "Nitrite Plus Nitrate (as N)", 
                   "Oil and Grease" = "Oil and Grease", 
                   "pH" = "pH",
                   "Phosphorus, Total (as P)" = "Phosphorus, Total (as P)", 
                   "Selenium, Total (Recoverable)" = "Selenium, Total (Recoverable)",       
                   "Total Suspended Solids (TSS)" = "Total Suspended Solids (TSS)",         
                   "Zinc, Total (Recoverable)" = "Zinc, Total (Recoverable)"), 
    selected = "All Pollutants")
```

This app displays facilities enrolled under the [Industrial General Permit](https://www.waterboards.ca.gov/water_issues/programs/stormwater/industrial.html) that have had discharges exceeding the permit's numeric action levels (NALs). Facilities that have violated NALs for a pollutant are elevated to "Level 1" and have to develop an Exceedance Response Action Level 1 Report. Facilities that continue to exceed NALs for a pollutant are elevated to "Level 2" and must complete an Exceedance Response Action Level 2 Action Plan.

Data was exported from [SMARTS](https://smarts.waterboards.ca.gov) on December 14, 2018.


Row {.tabset data-height=650}
-----------------------------------------------------------------------

### Map of Facilities
    
```{r}
selected_data <- sites

mapData <- shiny::reactive({
  if (as.character(input$Level) == "All Level 1 and Level 2 Facilities") {
    
  } else {
    selected_data <- sites %>%
      dplyr::filter(Level == as.character(input$Level))
  }
  
  if (as.character(input$Pollutant) == "All Pollutants") {
    
  } else {
    selected_data <- selected_data %>%
      dplyr::filter(Pollutant == as.character(input$Pollutant))
  }

  selected_data
    
})

# summaryData <- reactive({
#   mapData() %>%
#     dplyr::group_by(Primary.SIC.Code) %>%
#     dplyr::summarize(
#       count = n())
# })

graphData <- shiny::reactive({
  sites %>%
    dplyr::filter(Pollutant == as.character(input$Pollutant))
})

levelFilter <- shiny::reactive({
  input$Level
})

pollutantFilter <- shiny::reactive({
  input$Pollutant
})

leaflet::renderLeaflet({
  if (nrow(mapData()) == 0) {
    m <- leaflet() %>%
      addProviderTiles("Hydda.Full")
  } else {
    m <- leaflet() %>%
      addProviderTiles("Hydda.Full")
    
    m <- m %>%
      addMarkers(data = mapData(), clusterOptions = markerClusterOptions(),
                 popup = ~paste0('<b>', Facility, '</b></br>',
                                 'WDID: ', WDID, '</br>',
                                 Facility.Address, '</br>',
                                 Facility.City, ', CA ',
                                 Facility.Zip, '</br>',
                                 '<i>', Pollutant, '</br>',
                                 Level, '</i>'))
    
    m <- m %>% addPolygons(data=wma, stroke = TRUE, weight = 0.25, 
                           smoothFactor = 0.5, fillOpacity = 0.35,
                           fillColor = ~pal(WATERSHED), 
                           popup = ~paste("<B>", WATERSHED, "</B>", "<br>"))
  }
  
  m %>% setView(-118.2437, 34.0522, zoom = 8)
  
})
```

### Table of Facilities

```{r}
DT::renderDataTable({
  DT::datatable(mapData(),
                  options = list(pageLength = 10, scrollY = "275px", paging = FALSE, scrollX = "450"),
                  rownames = FALSE)
})

```

Row {data-height=350}
-----------------------------------------------------------------------

### Bar Graph

```{r}

shiny::renderPlot({
  ggplot2::ggplot(mapData(), aes(Level)) +
    ggplot2::geom_bar(stat="count", aes(fill = Level)) +
    ggplot2::coord_flip() +
    ggplot2::ggtitle(paste0("Count of Level 1 and 2 Facilities")) +
    ggplot2::theme_classic() +
    ggplot2::theme(legend.position = "bottom") +
    ggplot2::scale_fill_manual(values=c("orange", "red"))
})

```

### Pollutant Treemap

```{r}

# summary <- mapData() %>% 
#   dplyr::group_by(Primary.SIC.Code) %>%
#   dplyr::summarize(
#     count = n()
#   )

# summary <- reactive({
#   summary <- summaryData()
#   summary
# })
# 
# pl <- ggplot2::ggplot(summary) +
#   geom_bar(stat="count", aes(fill = Primary.SIC.Code)) +
#   coord_flip() +
#   ggtitle(paste0("Count of Level 1 and 2 Facilities")) +
#   theme_classic() +
#   theme(legend.position = "bottom")
# 

treedata <- sites %>%
  dplyr::group_by(Pollutant, Level) %>%
  dplyr::summarise(Total = n())

tm <- treemap::treemap(treedata, index = c("Pollutant"), vSize = "Total")


```